# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pry < Formula
  desc "Terminal UI for reviewing GitHub pull requests"
  homepage "https://github.com/jethrokuan/pry"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.4/pry_0.0.4_darwin_amd64.tar.gz"
      sha256 "42ebfff34c04bf999ea8c55d0138e4f898fb9a6ca2025f5b8cb1ed7c919bffd0"

      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.4/pry_0.0.4_darwin_arm64.tar.gz"
      sha256 "734f77c98c76d1252b476e93510fa15379bd7975f3482a2fdeefa300dc6e1233"

      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.4/pry_0.0.4_linux_amd64.tar.gz"
      sha256 "736abca560f451defc5d13bde8a5d56b845cd71a1b65021fdcc8d0091a698e55"
      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.4/pry_0.0.4_linux_arm64.tar.gz"
      sha256 "3a60c0f5d5218edc64633329e91107c4ea09f8db6dba9646c2152eb5bc611b24"
      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  test do
    system "#{bin}/pry", "--version"
  end
end
