# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pry < Formula
  desc "Terminal UI for reviewing GitHub pull requests"
  homepage "https://github.com/jethrokuan/pry"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jethrokuan/pry/releases/download/v0.1.0/pry_0.1.0_darwin_amd64.tar.gz"
      sha256 "a1212063fbd89e29405ca7f88f979fa493e6cd0709b07a583c748c8b0d1f6fa5"

      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jethrokuan/pry/releases/download/v0.1.0/pry_0.1.0_darwin_arm64.tar.gz"
      sha256 "0d8ec0ca816732f2bc5651e027da6d79ddd08836b1bf4e4f3a77ceae4eb3bd7e"

      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.1.0/pry_0.1.0_linux_amd64.tar.gz"
      sha256 "097737e764b34f05bce403ff97bc18dc2c3e967ddc766479c3de31bfb905822c"
      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.1.0/pry_0.1.0_linux_arm64.tar.gz"
      sha256 "ffb79b2b67ca09f38d696498036f38a1b200b3cb52f780d06ab4d5bd21c9c68b"
      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  test do
    system "#{bin}/pry", "--version"
  end
end
