# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pry < Formula
  desc "Terminal UI for reviewing GitHub pull requests"
  homepage "https://github.com/jethrokuan/pry"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.5/pry_0.0.5_darwin_amd64.tar.gz"
      sha256 "3de5d1c8574286674a5f3d3e3051c8b447e2d445ecc310b4df4f09d185ced516"

      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.5/pry_0.0.5_darwin_arm64.tar.gz"
      sha256 "1ade5f10be12c48f45645bbf2969902775cf6d4477043003a7817fae403d4148"

      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.5/pry_0.0.5_linux_amd64.tar.gz"
      sha256 "c6b9d995d602cefe1aef6e91000de7fbb845af4bed60e3950a9604fff8c677ac"
      define_method(:install) do
        bin.install "pry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jethrokuan/pry/releases/download/v0.0.5/pry_0.0.5_linux_arm64.tar.gz"
      sha256 "808a5ef6ab9b809109b88ffb6fa7782ba85eabb43ea85606e825fcbfcb417037"
      define_method(:install) do
        bin.install "pry"
      end
    end
  end

  test do
    system "#{bin}/pry", "--version"
  end
end
